language: android
jdk: oraclejdk7
android:
  components:
    - tools
    - tools
    - android-24
    - build-tools-24.0.2
    - extra-android-support
    - extra-android-m2repository
  licenses:
    - android-sdk-license-.+
script:
  - ./gradlew assemble
